# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import federated_learning_pb2 as federated__learning__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_learning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningServiceStub(object):
    """Federated Learning Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinTraining = channel.unary_unary(
                '/federated_learning.FederatedLearningService/JoinTraining',
                request_serializer=federated__learning__pb2.JoinRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.SendModelWeights = channel.unary_unary(
                '/federated_learning.FederatedLearningService/SendModelWeights',
                request_serializer=federated__learning__pb2.ModelWeightsRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.ModelWeightsResponse.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/federated_learning.FederatedLearningService/GetGlobalModel',
                request_serializer=federated__learning__pb2.GlobalModelRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.GlobalModelResponse.FromString,
                _registered_method=True)
        self.SendMetrics = channel.unary_unary(
                '/federated_learning.FederatedLearningService/SendMetrics',
                request_serializer=federated__learning__pb2.MetricsRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.GetServerStatus = channel.unary_unary(
                '/federated_learning.FederatedLearningService/GetServerStatus',
                request_serializer=federated__learning__pb2.Empty.SerializeToString,
                response_deserializer=federated__learning__pb2.ServerStatusResponse.FromString,
                _registered_method=True)
        self.GetConnectedClients = channel.unary_unary(
                '/federated_learning.FederatedLearningService/GetConnectedClients',
                request_serializer=federated__learning__pb2.Empty.SerializeToString,
                response_deserializer=federated__learning__pb2.ConnectedClientsResponse.FromString,
                _registered_method=True)
        self.GetTrainingStats = channel.unary_unary(
                '/federated_learning.FederatedLearningService/GetTrainingStats',
                request_serializer=federated__learning__pb2.Empty.SerializeToString,
                response_deserializer=federated__learning__pb2.TrainingStatsResponse.FromString,
                _registered_method=True)


class FederatedLearningServiceServicer(object):
    """Federated Learning Service
    """

    def JoinTraining(self, request, context):
        """Client-side methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModelWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerStatus(self, request, context):
        """Admin-side monitoring methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectedClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinTraining,
                    request_deserializer=federated__learning__pb2.JoinRequest.FromString,
                    response_serializer=federated__learning__pb2.JoinResponse.SerializeToString,
            ),
            'SendModelWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelWeights,
                    request_deserializer=federated__learning__pb2.ModelWeightsRequest.FromString,
                    response_serializer=federated__learning__pb2.ModelWeightsResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=federated__learning__pb2.GlobalModelRequest.FromString,
                    response_serializer=federated__learning__pb2.GlobalModelResponse.SerializeToString,
            ),
            'SendMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMetrics,
                    request_deserializer=federated__learning__pb2.MetricsRequest.FromString,
                    response_serializer=federated__learning__pb2.MetricsResponse.SerializeToString,
            ),
            'GetServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerStatus,
                    request_deserializer=federated__learning__pb2.Empty.FromString,
                    response_serializer=federated__learning__pb2.ServerStatusResponse.SerializeToString,
            ),
            'GetConnectedClients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectedClients,
                    request_deserializer=federated__learning__pb2.Empty.FromString,
                    response_serializer=federated__learning__pb2.ConnectedClientsResponse.SerializeToString,
            ),
            'GetTrainingStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStats,
                    request_deserializer=federated__learning__pb2.Empty.FromString,
                    response_serializer=federated__learning__pb2.TrainingStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated_learning.FederatedLearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated_learning.FederatedLearningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearningService(object):
    """Federated Learning Service
    """

    @staticmethod
    def JoinTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/JoinTraining',
            federated__learning__pb2.JoinRequest.SerializeToString,
            federated__learning__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendModelWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/SendModelWeights',
            federated__learning__pb2.ModelWeightsRequest.SerializeToString,
            federated__learning__pb2.ModelWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/GetGlobalModel',
            federated__learning__pb2.GlobalModelRequest.SerializeToString,
            federated__learning__pb2.GlobalModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/SendMetrics',
            federated__learning__pb2.MetricsRequest.SerializeToString,
            federated__learning__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/GetServerStatus',
            federated__learning__pb2.Empty.SerializeToString,
            federated__learning__pb2.ServerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectedClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/GetConnectedClients',
            federated__learning__pb2.Empty.SerializeToString,
            federated__learning__pb2.ConnectedClientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/GetTrainingStats',
            federated__learning__pb2.Empty.SerializeToString,
            federated__learning__pb2.TrainingStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
